# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(996, 536)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.EditDir = QtWidgets.QLineEdit(Form)
        self.EditDir.setObjectName("EditDir")
        self.verticalLayout_3.addWidget(self.EditDir)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.BtnChooseDir = QtWidgets.QPushButton(Form)
        self.BtnChooseDir.setObjectName("BtnChooseDir")
        self.horizontalLayout_3.addWidget(self.BtnChooseDir)
        self.BtnFlush = QtWidgets.QPushButton(Form)
        self.BtnFlush.setObjectName("BtnFlush")
        self.horizontalLayout_3.addWidget(self.BtnFlush)
        self.CheckMode = QtWidgets.QCheckBox(Form)
        self.CheckMode.setObjectName("CheckMode")
        self.horizontalLayout_3.addWidget(self.CheckMode)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.ListDir = QtWidgets.QListWidget(Form)
        self.ListDir.setObjectName("ListDir")
        self.verticalLayout_3.addWidget(self.ListDir)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.BtnStatus = QtWidgets.QPushButton(Form)
        self.BtnStatus.setObjectName("BtnStatus")
        self.horizontalLayout_4.addWidget(self.BtnStatus)
        self.BtnExportError = QtWidgets.QPushButton(Form)
        self.BtnExportError.setObjectName("BtnExportError")
        self.horizontalLayout_4.addWidget(self.BtnExportError)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.ListMain = QtWidgets.QListWidget(Form)
        self.ListMain.setObjectName("ListMain")
        self.verticalLayout.addWidget(self.ListMain)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.EditNow = QtWidgets.QLineEdit(Form)
        self.EditNow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.EditNow.setObjectName("EditNow")
        self.horizontalLayout_2.addWidget(self.EditNow)
        self.BtnGo = QtWidgets.QPushButton(Form)
        self.BtnGo.setObjectName("BtnGo")
        self.horizontalLayout_2.addWidget(self.BtnGo)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.ListCorrect = QtWidgets.QListWidget(Form)
        self.ListCorrect.setObjectName("ListCorrect")
        self.verticalLayout_2.addWidget(self.ListCorrect)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.ListError = QtWidgets.QListWidget(Form)
        self.ListError.setObjectName("ListError")
        self.verticalLayout_2.addWidget(self.ListError)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 4)
        self.horizontalLayout.setStretch(2, 3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.BtnChooseDir.clicked.connect(Form.chooseBtnClicked)
        self.BtnFlush.clicked.connect(Form.flushBtnClicked)
        self.BtnStatus.clicked.connect(Form.statusBtnClicked)
        self.BtnExportError.clicked.connect(Form.errorexportBtnClicked)
        self.BtnGo.clicked.connect(Form.goBtnClicked)
        self.ListDir.itemClicked['QListWidgetItem*'].connect(Form.dicClicked)
        self.EditNow.returnPressed.connect(self.BtnGo.click)
        self.BtnGo.clicked.connect(self.EditNow.clear)
        self.ListMain.currentRowChanged['int'].connect(Form.rowChanged)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "背词小助手"))
        self.EditDir.setPlaceholderText(_translate("Form", "请选择单词目录，留空为当前"))
        self.BtnChooseDir.setText(_translate("Form", "选择目录"))
        self.BtnFlush.setText(_translate("Form", "刷新"))
        self.CheckMode.setText(_translate("Form", "英译汉"))
        self.BtnStatus.setText(_translate("Form", "开始背词"))
        self.BtnExportError.setText(_translate("Form", "错误导出"))
        self.label.setText(_translate("Form", "Trans ->"))
        self.BtnGo.setText(_translate("Form", "Go"))
        self.label_2.setText(_translate("Form", "Correct"))
        self.label_3.setText(_translate("Form", "Wrong"))
